base_model: EleutherAI/pythia-1.4b-deduped
load_in_8bit: false
datasets:
  - path: gsm8k
    name: main
    train_on_split: train
    type: alpaca_chat.load_qa
dataset_prepared_path:
val_set_size: 0.05
adapter: ia3
lora_model_dir:
sequence_len: 256
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - query_key_value
lora_target_linear:
lora_fan_in_fan_out: true  # pythia/GPTNeoX lora specific
wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:
output_dir: ./lora-alpaca-pythia
gradient_accumulation_steps: 1
micro_batch_size: 4
num_epochs: 4
learning_rate: 3e-4
train_on_inputs: false
group_by_length: false
bf16: false
fp16: true
tf32: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
weight_decay: 0.1

# Logging
eval_steps: 0.05
save_strategy: epoch
saves_per_epoch: 1
logging_steps: 1